name: CI/CD Pipeline

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run tests
        run: |
          pytest -v

      - name: Build docker image
        run: |
          Docker build -t flask-ci-cd-demo .

      - name: Verify container starts
        run: |
          docker run -d -p 8000:8000 --name test-container dlask-c-cd-demo
          sleep 5
          curl -f https://localhost:8000/health
          docker stop test-container
          docker rm test-container